kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: log-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: log-reader-bind
subjects:
- kind: User
  name: employee01
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: employee99
  namespace: example
roleRef:
  kind: Role
  name: log-reader
  apiGroup: rbac.authorization.k8s.io
