kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: config-maintainer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "delete", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: config-maintainer-bind
subjects:
- kind: User
  name: employee02
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: config-maintainer
  apiGroup: rbac.authorization.k8s.io
