kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: deploy-auth
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pod", "service", "deployment", "replicaset", "job"]
  verbs: ["get", "list", "patch", "update", "delete", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: deploy-auth-bind
subjects:
- kind: User
  name: employee03
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy-auth
  apiGroup: rbac.authorization.k8s.io
